#+title: sand

* What is this?

Once I was playing Minecraft and thought that it wasn't a game that I liked enough. I wanted a sandbox game that was different. That different would focus on other things and I didnt want this game to become top down terraria. I wanted it to be something else. So here is a list of things I want (and they can change at any time btw).

** Features I want [0/9]

- [ ] Infinite worlds
- [ ] Loading a huge area for world simulation
- [ ] Procedural generation everywhere (so I can be lazy and also the game has more diversity)
- [ ] Automation at its finest
- [ ] Intelliegnt NPC with comunities/society
- [ ] Realistic crafting and building
  - To build a structure you need to bring and install resources
- [ ] Dymamic biomes that change based on the climate
- [ ] Realistic inventory
  - Items have weight, volume, etc and containers/vehicles have limitations

* How am I going to get there?

** ECS

- ECS :: Entity Compoment System

Why I chose ECS? That is because it promises to be pretty fast and it has a rather simple approach to thigns:

1) Give me a list of all the objects that have certain qualities
2) Update data on them with a given function
3) Do the same for another system

This approach may not be the best for some applications, but I think its going to be perfect for prototyping. When you dont know what you will have in the end and not having a defined journey to that end its

* BUILDING

Platform: Arch Linux

Dependencies:

- Box2d ([[https://github.com/erincatto/box2d][Github]], [[https://github.com/erincatto/box2d][Website/Docs]]) :: Installed with =pacman -S box2d=
- SDL2 ([[https://github.com/libsdl-org/SDL][Github]],[[https://libsdl.org][Website/Docs]]) :: Installed with =pacman -S sdl2=
- EnTT ([[https://github.com/skypjack/entt][Github]]) :: See [[https://github.com/skypjack/entt#packaging-tools][#Packaging Tools]] for installation instructions
- Imgui ([[/][Github]]) :: Installed with =yay -S imgui= and copied backend code in =include/dependencies= and =src/dependencies=.

This is a cmake project. Build it with:

#+begin_src shell
# in project root
cmake -S . -B build
cmake --build build/ -j 4
#+end_src

Check Cmake files for location of the executable. It should be in =build/src/sand_main=.
